name: 'Coveralls Python'
author: 'Andre Miras'
description: 'Python coverage reports via coveralls.io'
branding:
  color: 'green'
  icon: 'percent'
inputs:
  github-token:
    description: 'The `GITHUB_TOKEN` or `COVERALLS_REPO_TOKEN`'
    default: ${{ github.token }}
  parallel:
    description: 'Set to true if you are running parallel jobs, then use `parallel-finished: true` for the last action'
    default: false
  parallel-finished:
    description: 'Set to true for the last action when using `parallel: true`'
    default: false
  debug:
    description: 'Set to `true` to increase logger verbosity'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --github-token
    - ${{ inputs.github-token }}
    - --parallel
    - ${{ inputs.parallel }}
    - --parallel-finished
    - ${{ inputs.parallel-finished }}
    - --debug
    - ${{ inputs.debug }}
