name: push
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1

    - name: Unit tests
      run: make test

    - name: Default arguments
      uses: ./

    - name: With --github-token GITHUB_TOKEN
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: With --github-token COVERALLS_REPO_TOKEN
      uses: ./
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: With --debug
      uses: ./
      with:
        debug: true

    - name: With --parallel
      uses: ./
      with:
        parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Coveralls Finished
      uses: ./
      with:
        parallel-finished: true
        debug: true
